version: '3'

networks:
  whaticket:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgresql
      - DB_USER=root
      - DB_PASS=${DB_PASS:-strongpassword}
      - DB_NAME=${DB_NAME:-whaticket}
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PROXY_PORT=${PROXY_PORT:-8080}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    ports:
      - ${BACKEND_PORT:-8080}:3000
    volumes:
      - ./backend/public/:/usr/src/app/public/
    networks:
      - whaticket

  frontend:
    ports:
      - ${FRONTEND_PORT:-3000}:80
      - ${FRONTEND_SSL_PORT:-3001}:443
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - URL_BACKEND=backend:3000
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost}:${PROXY_PORT:-8080}/
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
    volumes:
      - ./ssl/certs/:/etc/nginx/ssl/
      - ./ssl/www/:/var/www/letsencrypt/
    networks:
      - whaticket

  postgresql:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${DB_PASS:-strongpassword}
      - POSTGRES_DB=${DB_NAME:-whaticket}
      - TZ=${TZ:-America/Fortaleza}
    volumes:
      - ./.docker/db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - whaticket

  redis:
    image: redis:alpine
    restart: always
    networks:
      - whaticket